title:              Ximena Sandoval
email:              ximena.sandoval.dh@gmail.com
description:        Sometimes I code
author:             Ximena Sandoval
baseurl:            ""
url:                "https://ximenasandoval.github.io/"

# Social Profiles
twitter_username:   control_freeak
github_username:    ximenasandoval
# facebook_username:  StartBootstrap
# instagram_username:  
linkedin_username:  ximena-sandoval-3032221b3

# Add your google-analytics ID here to activate google analytics
# google_analytics:   251207899 UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown: kramdown

paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  - jemoji